### PR TITLE
Initial addition of STI image test framework (local)

### PR DESCRIPTION
**Pull request by mfojtik**
This is an initial addition of the 'test framework' (as described in https://trello.com/c/d845L5f1/445-5-sti-local-test-operation).

Similar `test/` directories will be added into wildfly image soon, but I want to first discuss the design/etc here. 

UPDATED workflow:

* As a STI image author I want to be able to test changes in my STI image and make sure all STI scripts operate properly. To do that, I will:

1. Add `test` directory to my STI image GIT repository
2. Add `test/run` command to that repository, this command will then:
3. Take the example application source code (`test/test-app`) and build a 'testapp' image using `sti build` (this part will be revisited in future and moved to STI itself)
4. Once the testapp image is successfully built, I can trigger the build again to make sure the `save-artifacts` and `restore-artifacts` operatesproperly
5. Then the script test the `usage` script
6. Then the script run the testapp image and verify that it is responding to HTTP calls
7. (optionally) I can run `docker exec` and inspect the testapp container OR perform any other needed tests to exercise the `run` script properly started my application and `asseble` properly installed all required things.
8. The `test/run` script then report the exit code as result (0 = success) 

It is up to image author what he will put into `test/run`, we do care about the return code which indicate success or failure.

The `test/run` takes just one argument for now which is a image name (openshift/ruby-20-centos-candidate) that will be used for the test.

This ultimately allow us to create a `openshift/sti-image-builder` Docker image, that will execute all the above and promote the image by tagging it or pushing into imageRepository using the CustomBuild.

The only requirement for the `openshift/sti-image-builder` is that it needs to have 'sti' command installed (which is not possible atm. other than 'building it from source' or having a static binary).

@bparees @soltysh

### CODE REVIEW

**Comment by bparees** [comment]
this looks good to me so far.

**Comment by mfojtik** [comment]
@bparees K, going to do the same for wildfly and going to kick the customBuild.

**Comment by mfojtik** [comment]
[merge]

**Comment by mfojtik** [comment]
@danmcp it seems like I loose the 'merge' button rights for this repo :-(

**Pull request merged**
